title: Reintegration Handbook
description: Practical guidance on the design, implementation and monitoring of reintegration assistance

theme: null

debug:
  compress: true
  dist: false
  shortcodes: false
  
host: 0.0.0.0

readme_index:
  with_frontmatter: true

plugins:
  - jemoji
  - jekyll-avatar
  - jekyll-mentions
#  - jekyll-offline
  - jekyll-multiple-languages-plugin

exclude:
  - Makefile
  - CNAME
  - LICENSE
  - update.sh
  - Gemfile
  - Gemfile.lock
  - requirements.txt
  - node_modules
  - package.json
  - package-lock.json
  - webpack.config.js
  - jekyll-rtd-theme.gemspec
  - common/assets/sw.caches.js

offline:
 strategy: cache-first-network-fallback

repository: GerardTo/jekyll-rtd-theme

pwa:
  sw_src_filepath: service-worker.js # Optional
  sw_dest_filename: service-worker.js # Optional
  dest_js_directory: assets/js # Required
  precache_recent_posts_num: 5 # Optional
  precache_glob_directory: / # Optional
  precache_glob_patterns: # Optional
    - "/**/*.{js,json,css}"
    - "/**/*.{ico,jpg,jpeg,png,svg}"
    - "/**/*.html"
  precache_glob_ignores: # Optional
    - "sw-register.js"
    - "fonts/**/*"